// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#include "bv4.hpp"

#include "bv2.hpp"
#include "bv3.hpp"
#include "bv4.hpp"
#include "fv4.hpp"
#include "dv4.hpp"
#include "iv4.hpp"
#include "s64v4.hpp"
#include "u8v4.hpp"

namespace vector {
	
	
	// extend vector
	bv4::bv4 (bv2 xy, bool z, bool w): x{xy.x}, y{xy.y}, z{z}, w{w} {
		
	}
	
	// extend vector
	bv4::bv4 (bv3 xyz, bool w): x{xyz.x}, y{xyz.y}, z{xyz.z}, w{w} {
		
	}
	
	//// Truncating cast operators
	
	
	bv4::operator bv2 () const {
		return bv2(x, y);
	}
	
	bv4::operator bv3 () const {
		return bv3(x, y, z);
	}
	
	//// Type cast operators
	
	
	//// reducing ops
	
	// all components are true
	bool all (bv4 v) {
		return v.x && v.y && v.z && v.w;
	}
	
	// any components is true
	bool any (bv4 v) {
		return v.x || v.y || v.z || v.w;
	}
	
	//// arthmethic ops
	
	//// comparison ops
	
	bv4 operator== (bv4 l, bv4 r) {
		return bv4(l.x == r.x, l.y == r.y, l.z == r.z, l.w == r.w);
	}
	
	bv4 operator!= (bv4 l, bv4 r) {
		return bv4(l.x != r.x, l.y != r.y, l.z != r.z, l.w != r.w);
	}
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (bv4 l, bv4 r) {
		return all(l == r);
	}
	
	// componentwise ternary c ? l : r
	bv4 select (bv4 c, bv4 l, bv4 r) {
		return c.x ? l.x : r.x, c.y ? l.y : r.y, c.z ? l.z : r.z, c.w ? l.w : r.w;
	}
}// namespace vector

