// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "kissmath.hpp"


namespace vector {
	//// forward declarations
	union dv2;
	union dv3;
	union bv4;
	union bv4;
	union fv4;
	union iv4;
	union s64v4;
	union u8v4;
	
	union dv4 {
		struct {
			f64	x, y, z, w;
		};
		f64		arr[4];
		
		
		inline FORCEINLINE f64& operator[] (int i) {
			return arr[i];
		}
		
		inline FORCEINLINE f64 const& operator[] (int i) const {
			return arr[i];
		}
		
		
		inline FORCEINLINE dv4 () {
			
		}
		
		// sets all components to one value
		// implicit constructor -> v3(x,y,z) * 5 will be turned into v3(x,y,z) * v3(5) by to compiler to be able to execute operator*(v3, v3), which is desirable, also v3 a = 0; works
		inline FORCEINLINE dv4 (f64 all): x{all}, y{all}, z{all}, w{all} {
			
		}
		
		// supply all components
		inline FORCEINLINE dv4 (f64 x, f64 y, f64 z, f64 w): x{x}, y{y}, z{z}, w{w} {
			
		}
		// extend vector
		dv4 (dv2 xy, f64 z, f64 w);
		// extend vector
		dv4 (dv3 xyz, f64 w);
		
		//// Truncating cast operators
		
		explicit operator dv2 () const;
		explicit operator dv3 () const;
		
		//// Type cast operators
		
		explicit operator bv4 () const;
		explicit operator fv4 () const;
		explicit operator iv4 () const;
		explicit operator s64v4 () const;
		explicit operator u8v4 () const;
		
		
		inline FORCEINLINE dv4 operator+= (dv4 r) {
			x += r.x;
			y += r.y;
			z += r.z;
			w += r.w;
			return *this;
		}
		
		inline FORCEINLINE dv4 operator-= (dv4 r) {
			x -= r.x;
			y -= r.y;
			z -= r.z;
			w -= r.w;
			return *this;
		}
		
		inline FORCEINLINE dv4 operator*= (dv4 r) {
			x *= r.x;
			y *= r.y;
			z *= r.z;
			w *= r.w;
			return *this;
		}
		
		inline FORCEINLINE dv4 operator/= (dv4 r) {
			x /= r.x;
			y /= r.y;
			z /= r.z;
			w /= r.w;
			return *this;
		}
	};
	
	//// arthmethic ops
	
	inline FORCEINLINE dv4 operator+ (dv4 v) {
		return dv4(+v.x, +v.y, +v.z, +v.w);
	}
	
	inline FORCEINLINE dv4 operator- (dv4 v) {
		return dv4(-v.x, -v.y, -v.z, -v.w);
	}
	
	inline FORCEINLINE dv4 operator+ (dv4 l, dv4 r) {
		return dv4(l.x + r.x, l.y + r.y, l.z + r.z, l.w + r.w);
	}
	
	inline FORCEINLINE dv4 operator- (dv4 l, dv4 r) {
		return dv4(l.x - r.x, l.y - r.y, l.z - r.z, l.w - r.w);
	}
	
	inline FORCEINLINE dv4 operator* (dv4 l, dv4 r) {
		return dv4(l.x * r.x, l.y * r.y, l.z * r.z, l.w * r.w);
	}
	
	inline FORCEINLINE dv4 operator/ (dv4 l, dv4 r) {
		return dv4(l.x / r.x, l.y / r.y, l.z / r.z, l.w / r.w);
	}
	
	//// comparison ops
	bv4 operator< (dv4 l, dv4 r);
	bv4 operator<= (dv4 l, dv4 r);
	bv4 operator> (dv4 l, dv4 r);
	bv4 operator>= (dv4 l, dv4 r);
	bv4 operator== (dv4 l, dv4 r);
	bv4 operator!= (dv4 l, dv4 r);
	// vectors are equal, equivalent to all(l == r)
	bool equal (dv4 l, dv4 r);
	// componentwise ternary c ? l : r
	dv4 select (bv4 c, dv4 l, dv4 r);
	
	//// misc ops
	
	inline FORCEINLINE dv4 abs (dv4 v) {
		return dv4(abs(v.x), abs(v.y), abs(v.z), abs(v.w));
	}
	
	inline FORCEINLINE dv4 min (dv4 l, dv4 r) {
		return dv4(min(l.x,r.x), min(l.y,r.y), min(l.z,r.z), min(l.w,r.w));
	}
	
	inline FORCEINLINE dv4 max (dv4 l, dv4 r) {
		return dv4(max(l.x,r.x), max(l.y,r.y), max(l.z,r.z), max(l.w,r.w));
	}
	dv4 clamp (dv4 x, dv4 a=dv4(0), dv4 b=dv4(1));
	// get min component of vector, optionally get component index via min_index
	f64 min_component (dv4 v, int* min_index=nullptr);
	// get max component of vector, optionally get component index via max_index
	f64 max_component (dv4 v, int* max_index=nullptr);
	
	
	inline FORCEINLINE dv4 floor (dv4 v) {
		return dv4(floor(v.x), floor(v.y), floor(v.z), floor(v.w));
	}
	
	inline FORCEINLINE dv4 ceil (dv4 v) {
		return dv4(ceil(v.x), ceil(v.y), ceil(v.z), ceil(v.w));
	}
	
	inline FORCEINLINE dv4 round (dv4 v) {
		return dv4(round(v.x), round(v.y), round(v.z), round(v.w));
	}
	s64v4 floori (dv4 v);
	s64v4 ceili (dv4 v);
	s64v4 roundi (dv4 v);
	
	inline FORCEINLINE dv4 pow (dv4 v, dv4 e) {
		return dv4(pow(v.x,e.x), pow(v.y,e.y), pow(v.z,e.z), pow(v.w,e.w));
	}
	
	inline FORCEINLINE dv4 wrap (dv4 v, dv4 range) {
		return dv4(wrap(v.x,range.x), wrap(v.y,range.y), wrap(v.z,range.z), wrap(v.w,range.w));
	}
	
	inline FORCEINLINE dv4 wrap (dv4 v, dv4 a, dv4 b) {
		return dv4(wrap(v.x,a.x,b.x), wrap(v.y,a.y,b.y), wrap(v.z,a.z,b.z), wrap(v.w,a.w,b.w));
	}
	
	// linear interpolation t=0 -> a ; t=1 -> b ; t=0.5 -> (a+b)/2
	dv4 lerp (dv4 a, dv4 b, dv4 t);
	// linear mapping (reverse linear interpolation), map(70, 0,100) -> 0.7 ; map(0.5, -1,+1) -> 0.75
	dv4 map (dv4 x, dv4 in_a, dv4 in_b);
	// linear mapping, lerp(out_a, out_b, map(x, in_a, in_b))
	dv4 map (dv4 x, dv4 in_a, dv4 in_b, dv4 out_a, dv4 out_b);
	
	//// angle stuff
	dv4 to_rad (dv4 deg);
	// degress "literal", converts degrees to radiants
	dv4 deg (dv4 deg);
	dv4 to_deg (dv4 rad);
	
	//// linear algebra ops
	// magnitude of vector
	f64 length (dv4 v);
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	f64 length_sqr (dv4 v);
	// distance between points, equivalent to length(a - b)
	f64 distance (dv4 a, dv4 b);
	// normalize vector so that it has length() = 1, undefined for zero vector
	dv4 normalize (dv4 v);
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	dv4 normalize_or_zero (dv4 v);
	// dot product
	f64 dot (dv4 l, dv4 r);
}// namespace vector

