// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "kissmath.hpp"


namespace vector {
	//// forward declarations
	struct fv3;
	struct fv4;
	struct bv2;
	struct bv2;
	struct dv2;
	struct iv2;
	struct s64v2;
	struct u8v2;
	
	struct fv2 {
		union {
			struct {
				f32	x, y;
			};
			f32		arr[2];
		};
		
		inline FORCEINLINE f32& operator[] (int i) {
			return arr[i];
		}
		
		inline FORCEINLINE f32 const& operator[] (int i) const {
			return arr[i];
		}
		
		
		inline FORCEINLINE fv2 () {
			
		}
		
		// sets all components to one value
		// implicit constructor -> v3(x,y,z) * 5 will be turned into v3(x,y,z) * v3(5) by to compiler to be able to execute operator*(v3, v3), which is desirable, also v3 a = 0; works
		inline FORCEINLINE fv2 (f32 all): x{all}, y{all} {
			
		}
		
		// supply all components
		inline FORCEINLINE fv2 (f32 x, f32 y): x{x}, y{y} {
			
		}
		// truncate vector
		fv2 (fv3 v);
		// truncate vector
		fv2 (fv4 v);
		
		//// Truncating cast operators
		
		
		//// Type cast operators
		
		explicit operator bv2 () const;
		explicit operator dv2 () const;
		explicit operator iv2 () const;
		explicit operator s64v2 () const;
		explicit operator u8v2 () const;
		
		
		inline FORCEINLINE fv2 operator+= (fv2 r) {
			x += r.x;
			y += r.y;
			return *this;
		}
		
		inline FORCEINLINE fv2 operator-= (fv2 r) {
			x -= r.x;
			y -= r.y;
			return *this;
		}
		
		inline FORCEINLINE fv2 operator*= (fv2 r) {
			x *= r.x;
			y *= r.y;
			return *this;
		}
		
		inline FORCEINLINE fv2 operator/= (fv2 r) {
			x /= r.x;
			y /= r.y;
			return *this;
		}
	};
	
	//// arthmethic ops
	
	inline FORCEINLINE fv2 operator+ (fv2 v) {
		return fv2(+v.x, +v.y);
	}
	
	inline FORCEINLINE fv2 operator- (fv2 v) {
		return fv2(-v.x, -v.y);
	}
	
	inline FORCEINLINE fv2 operator+ (fv2 l, fv2 r) {
		return fv2(l.x + r.x, l.y + r.y);
	}
	
	inline FORCEINLINE fv2 operator- (fv2 l, fv2 r) {
		return fv2(l.x - r.x, l.y - r.y);
	}
	
	inline FORCEINLINE fv2 operator* (fv2 l, fv2 r) {
		return fv2(l.x * r.x, l.y * r.y);
	}
	
	inline FORCEINLINE fv2 operator/ (fv2 l, fv2 r) {
		return fv2(l.x / r.x, l.y / r.y);
	}
	
	//// comparison ops
	bv2 operator< (fv2 l, fv2 r);
	bv2 operator<= (fv2 l, fv2 r);
	bv2 operator> (fv2 l, fv2 r);
	bv2 operator>= (fv2 l, fv2 r);
	bv2 operator== (fv2 l, fv2 r);
	bv2 operator!= (fv2 l, fv2 r);
	// vectors are equal, equivalent to all(l == r)
	bool equal (fv2 l, fv2 r);
	// componentwise ternary c ? l : r
	fv2 select (bv2 c, fv2 l, fv2 r);
	
	//// misc ops
	
	inline FORCEINLINE fv2 abs (fv2 v) {
		return fv2(abs(v.x), abs(v.y));
	}
	
	inline FORCEINLINE fv2 min (fv2 l, fv2 r) {
		return fv2(min(l.x,r.x), min(l.y,r.y));
	}
	
	inline FORCEINLINE fv2 max (fv2 l, fv2 r) {
		return fv2(max(l.x,r.x), max(l.y,r.y));
	}
	fv2 clamp (fv2 x, fv2 a=fv2(0), fv2 b=fv2(1));
	// get min component of vector, optionally get component index via min_index
	f32 min_component (fv2 v, int* min_index=nullptr);
	// get max component of vector, optionally get component index via max_index
	f32 max_component (fv2 v, int* max_index=nullptr);
	
	
	inline FORCEINLINE fv2 floor (fv2 v) {
		return fv2(floor(v.x), floor(v.y));
	}
	
	inline FORCEINLINE fv2 ceil (fv2 v) {
		return fv2(ceil(v.x), ceil(v.y));
	}
	
	inline FORCEINLINE fv2 round (fv2 v) {
		return fv2(round(v.x), round(v.y));
	}
	iv2 floori (fv2 v);
	iv2 ceili (fv2 v);
	iv2 roundi (fv2 v);
	
	inline FORCEINLINE fv2 pow (fv2 v, fv2 e) {
		return fv2(pow(v.x,e.x), pow(v.y,e.y));
	}
	
	inline FORCEINLINE fv2 wrap (fv2 v, fv2 range) {
		return fv2(wrap(v.x,range.x), wrap(v.y,range.y));
	}
	
	inline FORCEINLINE fv2 wrap (fv2 v, fv2 a, fv2 b) {
		return fv2(wrap(v.x,a.x,b.x), wrap(v.y,a.y,b.y));
	}
	
	// linear interpolation t=0 -> a ; t=1 -> b ; t=0.5 -> (a+b)/2
	fv2 lerp (fv2 a, fv2 b, fv2 t);
	// linear mapping (reverse linear interpolation), map(70, 0,100) -> 0.7 ; map(0.5, -1,+1) -> 0.75
	fv2 map (fv2 x, fv2 in_a, fv2 in_b);
	// linear mapping, lerp(out_a, out_b, map(x, in_a, in_b))
	fv2 map (fv2 x, fv2 in_a, fv2 in_b, fv2 out_a, fv2 out_b);
	
	//// angle stuff
	fv2 to_rad (fv2 deg);
	// degress "literal", converts degrees to radiants
	fv2 deg (fv2 deg);
	fv2 to_deg (fv2 rad);
	
	//// linear algebra ops
	// magnitude of vector
	f32 length (fv2 v);
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	f32 length_sqr (fv2 v);
	// distance between points, equivalent to length(a - b)
	f32 distance (fv2 a, fv2 b);
	// normalize vector so that it has length() = 1, undefined for zero vector
	fv2 normalize (fv2 v);
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	fv2 normalize_or_zero (fv2 v);
	// dot product
	f32 dot (fv2 l, fv2 r);
	// 
	// 2d cross product hack for convinient 2d stuff
	// same as cross(v3(l, 0), v3(r, 0)).z,
	// ie. the cross product of the 2d vectors on the z=0 plane in 3d space and then return the z coord of that (signed mag of cross product)
	// 
	f32 cross (fv2 l, fv2 r);
	// rotate 2d vector counterclockwise 90 deg, ie. fv2(-y, x) which is fast
	fv2 rotate90 (fv2 v);
}// namespace vector

