// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#include "s64v2.hpp"

#include "s64v3.hpp"
#include "s64v4.hpp"
#include "bv2.hpp"
#include "bv2.hpp"
#include "fv2.hpp"
#include "dv2.hpp"
#include "iv2.hpp"
#include "u8v2.hpp"

namespace vector {
	
	
	// truncate vector
	s64v2::s64v2 (s64v3 v): x{v.x}, y{v.y} {
		
	}
	
	// truncate vector
	s64v2::s64v2 (s64v4 v): x{v.x}, y{v.y} {
		
	}
	
	//// Truncating cast operators
	
	
	//// Type cast operators
	
	
	s64v2::operator bv2 () const {
		return bv2((bool)x, (bool)y);
	}
	
	s64v2::operator fv2 () const {
		return fv2((f32)x, (f32)y);
	}
	
	s64v2::operator dv2 () const {
		return dv2((f64)x, (f64)y);
	}
	
	s64v2::operator iv2 () const {
		return iv2((s32)x, (s32)y);
	}
	
	s64v2::operator u8v2 () const {
		return u8v2((u8)x, (u8)y);
	}
	
	
	//// arthmethic ops
	
	//// comparison ops
	
	bv2 operator< (s64v2 l, s64v2 r) {
		return bv2(l.x < r.x, l.y < r.y);
	}
	
	bv2 operator<= (s64v2 l, s64v2 r) {
		return bv2(l.x <= r.x, l.y <= r.y);
	}
	
	bv2 operator> (s64v2 l, s64v2 r) {
		return bv2(l.x > r.x, l.y > r.y);
	}
	
	bv2 operator>= (s64v2 l, s64v2 r) {
		return bv2(l.x >= r.x, l.y >= r.y);
	}
	
	bv2 operator== (s64v2 l, s64v2 r) {
		return bv2(l.x == r.x, l.y == r.y);
	}
	
	bv2 operator!= (s64v2 l, s64v2 r) {
		return bv2(l.x != r.x, l.y != r.y);
	}
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (s64v2 l, s64v2 r) {
		return all(l == r);
	}
	
	// componentwise ternary c ? l : r
	s64v2 select (bv2 c, s64v2 l, s64v2 r) {
		return c.x ? l.x : r.x, c.y ? l.y : r.y;
	}
	
	//// misc ops
	
	s64v2 clamp (s64v2 x, s64v2 a, s64v2 b) {
		return min(max(x,a), b);
	}
	
	// get min component of vector, optionally get component index via min_index
	s64 min_component (s64v2 v, int* min_index) {
		int index = 0;
		s64 min_val = v.x;	
		for (int i=1; i<2; ++i) {
			if (v.arr[i] <= min_val) {
				index = i;
				min_val = v.arr[i];
			}
		}
		if (min_index) *min_index = index;
		return min_val;
	}
	
	// get max component of vector, optionally get component index via max_index
	s64 max_component (s64v2 v, int* max_index) {
		int index = 0;
		s64 max_val = v.x;	
		for (int i=1; i<2; ++i) {
			if (v.arr[i] >= max_val) {
				index = i;
				max_val = v.arr[i];
			}
		}
		if (max_index) *max_index = index;
		return max_val;
	}
	
	
	
	dv2 to_rad (s64v2 deg) {
		return (dv2)deg * DEG_TO_RADd;
	}
	
	// degress "literal", converts degrees to radiants
	dv2 deg (s64v2 deg) {
		return (dv2)deg * DEG_TO_RADd;
	}
	
	dv2 to_deg (s64v2 rad) {
		return (dv2)rad * RAD_TO_DEGd;
	}
	
	//// linear algebra ops
	
	// magnitude of vector
	f64 length (s64v2 v) {
		return sqrt((f64)(v.x * v.x + v.y * v.y));
	}
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	s64 length_sqr (s64v2 v) {
		return v.x * v.x + v.y * v.y;
	}
	
	// distance between points, equivalent to length(a - b)
	f64 distance (s64v2 a, s64v2 b) {
		return length(a - b);
	}
	
	// normalize vector so that it has length() = 1, undefined for zero vector
	dv2 normalize (s64v2 v) {
		return dv2(v) / length(v);
	}
	
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	dv2 normalize_or_zero (s64v2 v) {
		f64 len = length(v);
		if (len == f64(0)) {
			return f64(0);
		}
		return dv2(v) / dv2(len);
	}
	
	// dot product
	s64 dot (s64v2 l, s64v2 r) {
		return l.x * r.x + l.y * r.y;
	}
	
	// 
	// 2d cross product hack for convinient 2d stuff
	// same as cross(v3(l, 0), v3(r, 0)).z,
	// ie. the cross product of the 2d vectors on the z=0 plane in 3d space and then return the z coord of that (signed mag of cross product)
	// 
	s64 cross (s64v2 l, s64v2 r) {
		return l.x * r.y - l.y * r.x;
	}
	
	// rotate 2d vector counterclockwise 90 deg, ie. s64v2(-y, x) which is fast
	s64v2 rotate90 (s64v2 v) {
		return s64v2(-v.y, v.x);
	}
}// namespace vector

