// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "stdint.h"
namespace vector {
	typedef signed char			schar;
	typedef unsigned char		uchar;
	typedef short				sshort;
	typedef unsigned short		ushort;
	typedef int					sint;
	typedef unsigned int		uint;
	typedef long				slong;
	typedef unsigned long		ulong;
	typedef long long			sllong;
	typedef unsigned long long	ullong;
	
	typedef int8_t				s8;
	typedef uint8_t				u8;
	typedef int16_t				s16;
	typedef uint16_t			u16;
	typedef int32_t				s32;
	typedef uint32_t			u32;
	typedef int64_t				s64;
	typedef uint64_t			u64;
	
	typedef u8					byte;
	
	typedef intptr_t			sptr;
	typedef uintptr_t			uptr;
	
	typedef float				f32;
	typedef double				f64;
}
