// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "kissmath.hpp"


namespace vector {
	//// forward declarations
	union u8v2;
	union u8v3;
	union bv4;
	union bv4;
	union fv4;
	union dv4;
	union iv4;
	union s64v4;
	
	union u8v4 {
		struct {
			u8	x, y, z, w;
		};
		u8		arr[4];
		
		
		inline FORCEINLINE u8& operator[] (int i) {
			return arr[i];
		}
		
		inline FORCEINLINE u8 const& operator[] (int i) const {
			return arr[i];
		}
		
		
		inline FORCEINLINE u8v4 () {
			
		}
		
		// sets all components to one value
		// implicit constructor -> v3(x,y,z) * 5 will be turned into v3(x,y,z) * v3(5) by to compiler to be able to execute operator*(v3, v3), which is desirable, also v3 a = 0; works
		inline FORCEINLINE u8v4 (u8 all): x{all}, y{all}, z{all}, w{all} {
			
		}
		
		// supply all components
		inline FORCEINLINE u8v4 (u8 x, u8 y, u8 z, u8 w): x{x}, y{y}, z{z}, w{w} {
			
		}
		// extend vector
		u8v4 (u8v2 xy, u8 z, u8 w);
		// extend vector
		u8v4 (u8v3 xyz, u8 w);
		
		//// Truncating cast operators
		
		explicit operator u8v2 () const;
		explicit operator u8v3 () const;
		
		//// Type cast operators
		
		explicit operator bv4 () const;
		explicit operator fv4 () const;
		explicit operator dv4 () const;
		explicit operator iv4 () const;
		explicit operator s64v4 () const;
		
		
		inline FORCEINLINE u8v4 operator+= (u8v4 r) {
			x += r.x;
			y += r.y;
			z += r.z;
			w += r.w;
			return *this;
		}
		
		inline FORCEINLINE u8v4 operator-= (u8v4 r) {
			x -= r.x;
			y -= r.y;
			z -= r.z;
			w -= r.w;
			return *this;
		}
		
		inline FORCEINLINE u8v4 operator*= (u8v4 r) {
			x *= r.x;
			y *= r.y;
			z *= r.z;
			w *= r.w;
			return *this;
		}
		
		inline FORCEINLINE u8v4 operator/= (u8v4 r) {
			x /= r.x;
			y /= r.y;
			z /= r.z;
			w /= r.w;
			return *this;
		}
	};
	
	//// arthmethic ops
	
	inline FORCEINLINE u8v4 operator+ (u8v4 v) {
		return u8v4(+v.x, +v.y, +v.z, +v.w);
	}
	
	inline FORCEINLINE u8v4 operator- (u8v4 v) {
		return u8v4(-v.x, -v.y, -v.z, -v.w);
	}
	
	inline FORCEINLINE u8v4 operator+ (u8v4 l, u8v4 r) {
		return u8v4(l.x + r.x, l.y + r.y, l.z + r.z, l.w + r.w);
	}
	
	inline FORCEINLINE u8v4 operator- (u8v4 l, u8v4 r) {
		return u8v4(l.x - r.x, l.y - r.y, l.z - r.z, l.w - r.w);
	}
	
	inline FORCEINLINE u8v4 operator* (u8v4 l, u8v4 r) {
		return u8v4(l.x * r.x, l.y * r.y, l.z * r.z, l.w * r.w);
	}
	
	inline FORCEINLINE u8v4 operator/ (u8v4 l, u8v4 r) {
		return u8v4(l.x / r.x, l.y / r.y, l.z / r.z, l.w / r.w);
	}
	
	//// comparison ops
	bv4 operator< (u8v4 l, u8v4 r);
	bv4 operator<= (u8v4 l, u8v4 r);
	bv4 operator> (u8v4 l, u8v4 r);
	bv4 operator>= (u8v4 l, u8v4 r);
	bv4 operator== (u8v4 l, u8v4 r);
	bv4 operator!= (u8v4 l, u8v4 r);
	// vectors are equal, equivalent to all(l == r)
	bool equal (u8v4 l, u8v4 r);
	// componentwise ternary c ? l : r
	u8v4 select (bv4 c, u8v4 l, u8v4 r);
	
	//// misc ops
	
	inline FORCEINLINE u8v4 abs (u8v4 v) {
		return u8v4(abs(v.x), abs(v.y), abs(v.z), abs(v.w));
	}
	
	inline FORCEINLINE u8v4 min (u8v4 l, u8v4 r) {
		return u8v4(min(l.x,r.x), min(l.y,r.y), min(l.z,r.z), min(l.w,r.w));
	}
	
	inline FORCEINLINE u8v4 max (u8v4 l, u8v4 r) {
		return u8v4(max(l.x,r.x), max(l.y,r.y), max(l.z,r.z), max(l.w,r.w));
	}
	u8v4 clamp (u8v4 x, u8v4 a=u8v4(0), u8v4 b=u8v4(1));
	// get min component of vector, optionally get component index via min_index
	u8 min_component (u8v4 v, int* min_index=nullptr);
	// get max component of vector, optionally get component index via max_index
	u8 max_component (u8v4 v, int* max_index=nullptr);
	
	
	inline FORCEINLINE u8v4 wrap (u8v4 v, u8v4 range) {
		return u8v4(wrap(v.x,range.x), wrap(v.y,range.y), wrap(v.z,range.z), wrap(v.w,range.w));
	}
	
	inline FORCEINLINE u8v4 wrap (u8v4 v, u8v4 a, u8v4 b) {
		return u8v4(wrap(v.x,a.x,b.x), wrap(v.y,a.y,b.y), wrap(v.z,a.z,b.z), wrap(v.w,a.w,b.w));
	}
	
	fv4 to_rad (u8v4 deg);
	// degress "literal", converts degrees to radiants
	fv4 deg (u8v4 deg);
	fv4 to_deg (u8v4 rad);
	
	//// linear algebra ops
	// magnitude of vector
	f32 length (u8v4 v);
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	u8 length_sqr (u8v4 v);
	// distance between points, equivalent to length(a - b)
	f32 distance (u8v4 a, u8v4 b);
	// normalize vector so that it has length() = 1, undefined for zero vector
	fv4 normalize (u8v4 v);
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	fv4 normalize_or_zero (u8v4 v);
	// dot product
	u8 dot (u8v4 l, u8v4 r);
}// namespace vector

