// bv2.hpp generated by vector_srcgen.py
#pragma once

#include "kissmath.hpp"

union bv2 {
	struct {
		bool	x, y;
	};
	bool		arr[2];

	inline bool& operator[] (int i) {
		return arr[i];
	}

	inline  bv2 () {
	
	}

	inline constexpr bv2 (bool all): x{all}, y{all} {
	
	}

	inline constexpr bv2 (bool x, bool y): x{x}, y{y} {
	
	}

