// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "kissmath.hpp"

//// forward declarations
union bv3;
union bv4;
union bv2;

union bv2 {
	struct {
		bool	x, y;
	};
	bool		arr[2];
	
	bool& operator[] (int i);
	bool operator[] (int i) const;
	
	bv2 ();
	// sets all components to one value
	constexpr bv2 (bool all);
	// supply all components
	constexpr bv2 (bool x, bool y);
	// truncate vector
	constexpr bv2 (bv3 v);
	// truncate vector
	constexpr bv2 (bv4 v);
	
};

//// reducing ops
// all components are true
constexpr bool all (bv2 v);
// any components is true
constexpr bool any (bv2 v);

//// arthmethic ops
constexpr bv2 operator! (bv2 v);
constexpr bv2 operator&& (bv2 l, bv2 r);
constexpr bv2 operator|| (bv2 l, bv2 r);

//// comparison ops
constexpr bv2 operator== (bv2 l, bv2 r);
constexpr bv2 operator!= (bv2 l, bv2 r);
// vectors are equal, equivalent to all(l == r)
constexpr bool equal (bv2 l, bv2 r);
// componentwise ternary c ? l : r
constexpr bv2 select (bv2 c, bv2 l, bv2 r);

