// bv4.hpp generated by vector_srcgen.py
#pragma once

#include "kissmath.hpp"

union bv4 {
	struct {
		bool	x, y, z, w;
	};
	bool		arr[4];

	inline bool& operator[] (int i) {
		return arr[i];
	}

	inline  bv4 () {
	
	}

	inline constexpr bv4 (bool all): x{all}, y{all}, z{all}, w{all} {
	
	}

	inline constexpr bv4 (bool x, bool y, bool z, bool w): x{x}, y{y}, z{z}, w{w} {
	
	}

