// dv2.hpp generated by vector_srcgen.py
#pragma once

#include "kissmath.hpp"

// forward declarations for conversion operators
union iv2;
union u8v2;

union dv2 {
	struct {
		f64	x, y;
	};
	f64		arr[2];

	inline f64& operator[] (int i) {
		return arr[i];
	}

	inline dv2 () {
	
	}

	inline constexpr dv2 (f64 all): x{all}, y{all} {
	
	}

	inline constexpr dv2 (f64 x, f64 y): x{x}, y{y} {
	
	}

	inline dv2 operator+= (dv2 r) {
		x += r.x;
		y += r.y;
		return *this;
	}
	inline dv2 operator-= (dv2 r) {
		x -= r.x;
		y -= r.y;
		return *this;
	}
	inline dv2 operator*= (dv2 r) {
		x *= r.x;
		y *= r.y;
		return *this;
	}
	inline dv2 operator/= (dv2 r) {
		x /= r.x;
		y /= r.y;
		return *this;
	}

	operator iv2 ();
	operator u8v2 ();
};

