// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#include "dv4.hpp"

#include "dv2.hpp"
#include "dv3.hpp"
#include "bv4.hpp"
#include "bv4.hpp"
#include "fv4.hpp"
#include "iv4.hpp"
#include "s64v4.hpp"
#include "u8v4.hpp"

namespace vector {
	
	f64& dv4::operator[] (int i) {
		return arr[i];
	}
	
	f64 const& dv4::operator[] (int i) const {
		return arr[i];
	}
	
	
	dv4::dv4 () {
		
	}
	
	// sets all components to one value
	// implicit constructor -> v3(x,y,z) * 5 will be turned into v3(x,y,z) * v3(5) by to compiler to be able to execute operator*(v3, v3), which is desirable, also v3 a = 0; works
	dv4::dv4 (f64 all): x{all}, y{all}, z{all}, w{all} {
		
	}
	
	// supply all components
	dv4::dv4 (f64 x, f64 y, f64 z, f64 w): x{x}, y{y}, z{z}, w{w} {
		
	}
	
	// extend vector
	dv4::dv4 (dv2 xy, f64 z, f64 w): x{xy.x}, y{xy.y}, z{z}, w{w} {
		
	}
	
	// extend vector
	dv4::dv4 (dv3 xyz, f64 w): x{xyz.x}, y{xyz.y}, z{xyz.z}, w{w} {
		
	}
	
	//// Truncating cast operators
	
	
	dv4::operator dv2 () const {
		return dv2(x, y);
	}
	
	dv4::operator dv3 () const {
		return dv3(x, y, z);
	}
	
	//// Type cast operators
	
	
	dv4::operator bv4 () const {
		return bv4((bool)x, (bool)y, (bool)z, (bool)w);
	}
	
	dv4::operator fv4 () const {
		return fv4((f32)x, (f32)y, (f32)z, (f32)w);
	}
	
	dv4::operator iv4 () const {
		return iv4((s32)x, (s32)y, (s32)z, (s32)w);
	}
	
	dv4::operator s64v4 () const {
		return s64v4((s64)x, (s64)y, (s64)z, (s64)w);
	}
	
	dv4::operator u8v4 () const {
		return u8v4((u8)x, (u8)y, (u8)z, (u8)w);
	}
	
	
	dv4 dv4::operator+= (dv4 r) {
		x += r.x;
		y += r.y;
		z += r.z;
		w += r.w;
		return *this;
	}
	
	dv4 dv4::operator-= (dv4 r) {
		x -= r.x;
		y -= r.y;
		z -= r.z;
		w -= r.w;
		return *this;
	}
	
	dv4 dv4::operator*= (dv4 r) {
		x *= r.x;
		y *= r.y;
		z *= r.z;
		w *= r.w;
		return *this;
	}
	
	dv4 dv4::operator/= (dv4 r) {
		x /= r.x;
		y /= r.y;
		z /= r.z;
		w /= r.w;
		return *this;
	}
	
	//// arthmethic ops
	
	dv4 operator+ (dv4 v) {
		return dv4(+v.x, +v.y, +v.z, +v.w);
	}
	
	dv4 operator- (dv4 v) {
		return dv4(-v.x, -v.y, -v.z, -v.w);
	}
	
	dv4 operator+ (dv4 l, dv4 r) {
		return dv4(l.x + r.x, l.y + r.y, l.z + r.z, l.w + r.w);
	}
	
	dv4 operator- (dv4 l, dv4 r) {
		return dv4(l.x - r.x, l.y - r.y, l.z - r.z, l.w - r.w);
	}
	
	dv4 operator* (dv4 l, dv4 r) {
		return dv4(l.x * r.x, l.y * r.y, l.z * r.z, l.w * r.w);
	}
	
	dv4 operator/ (dv4 l, dv4 r) {
		return dv4(l.x / r.x, l.y / r.y, l.z / r.z, l.w / r.w);
	}
	
	//// comparison ops
	
	bv4 operator< (dv4 l, dv4 r) {
		return bv4(l.x < r.x, l.y < r.y, l.z < r.z, l.w < r.w);
	}
	
	bv4 operator<= (dv4 l, dv4 r) {
		return bv4(l.x <= r.x, l.y <= r.y, l.z <= r.z, l.w <= r.w);
	}
	
	bv4 operator> (dv4 l, dv4 r) {
		return bv4(l.x > r.x, l.y > r.y, l.z > r.z, l.w > r.w);
	}
	
	bv4 operator>= (dv4 l, dv4 r) {
		return bv4(l.x >= r.x, l.y >= r.y, l.z >= r.z, l.w >= r.w);
	}
	
	bv4 operator== (dv4 l, dv4 r) {
		return bv4(l.x == r.x, l.y == r.y, l.z == r.z, l.w == r.w);
	}
	
	bv4 operator!= (dv4 l, dv4 r) {
		return bv4(l.x != r.x, l.y != r.y, l.z != r.z, l.w != r.w);
	}
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (dv4 l, dv4 r) {
		return all(l == r);
	}
	
	// componentwise ternary c ? l : r
	dv4 select (bv4 c, dv4 l, dv4 r) {
		return c.x ? l.x : r.x, c.y ? l.y : r.y, c.z ? l.z : r.z, c.w ? l.w : r.w;
	}
	
	//// misc ops
	
	dv4 abs (dv4 v) {
		return dv4(abs(v.x), abs(v.y), abs(v.z), abs(v.w));
	}
	
	dv4 min (dv4 l, dv4 r) {
		return dv4(min(l.x,r.x), min(l.y,r.y), min(l.z,r.z), min(l.w,r.w));
	}
	
	dv4 max (dv4 l, dv4 r) {
		return dv4(max(l.x,r.x), max(l.y,r.y), max(l.z,r.z), max(l.w,r.w));
	}
	
	dv4 clamp (dv4 x, dv4 a, dv4 b) {
		return min(max(x,a), b);
	}
	
	// get min component of vector, optionally get component index via min_index
	f64 min_component (dv4 v, int* min_index) {
		int index = 0;
		f64 min_val = v.x;	
		for (int i=1; i<4; ++i) {
			if (v.arr[i] <= min_val) {
				index = i;
				min_val = v.arr[i];
			}
		}
		if (min_index) *min_index = index;
		return min_val;
	}
	
	// get max component of vector, optionally get component index via max_index
	f64 max_component (dv4 v, int* max_index) {
		int index = 0;
		f64 max_val = v.x;	
		for (int i=1; i<4; ++i) {
			if (v.arr[i] >= max_val) {
				index = i;
				max_val = v.arr[i];
			}
		}
		if (max_index) *max_index = index;
		return max_val;
	}
	
	
	dv4 floor (dv4 v) {
		return dv4(floor(v.x), floor(v.y), floor(v.z), floor(v.w));
	}
	
	dv4 ceil (dv4 v) {
		return dv4(ceil(v.x), ceil(v.y), ceil(v.z), ceil(v.w));
	}
	
	dv4 round (dv4 v) {
		return dv4(round(v.x), round(v.y), round(v.z), round(v.w));
	}
	
	s64v4 floori (dv4 v) {
		return s64v4(floori(v.x), floori(v.y), floori(v.z), floori(v.w));
	}
	
	s64v4 ceili (dv4 v) {
		return s64v4(ceili(v.x), ceili(v.y), ceili(v.z), ceili(v.w));
	}
	
	s64v4 roundi (dv4 v) {
		return s64v4(roundi(v.x), roundi(v.y), roundi(v.z), roundi(v.w));
	}
	
	dv4 pow (dv4 v, dv4 e) {
		return dv4(pow(v.x,e.x), pow(v.y,e.y), pow(v.z,e.z), pow(v.w,e.w));
	}
	
	dv4 wrap (dv4 v, dv4 range) {
		return dv4(wrap(v.x,range.x), wrap(v.y,range.y), wrap(v.z,range.z), wrap(v.w,range.w));
	}
	
	dv4 wrap (dv4 v, dv4 a, dv4 b) {
		return dv4(wrap(v.x,a.x,b.x), wrap(v.y,a.y,b.y), wrap(v.z,a.z,b.z), wrap(v.w,a.w,b.w));
	}
	
	
	// linear interpolation t=0 -> a ; t=1 -> b ; t=0.5 -> (a+b)/2
	dv4 lerp (dv4 a, dv4 b, dv4 t) {
		return a * (dv4(1) - t) + b * t;
	}
	
	// linear mapping (reverse linear interpolation), map(70, 0,100) -> 0.7 ; map(0.5, -1,+1) -> 0.75
	dv4 map (dv4 x, dv4 in_a, dv4 in_b) {
		return (x - in_a) / (in_b - in_a);
	}
	
	// linear mapping, lerp(out_a, out_b, map(x, in_a, in_b))
	dv4 map (dv4 x, dv4 in_a, dv4 in_b, dv4 out_a, dv4 out_b) {
		return lerp(out_a, out_b, map(x, in_a, in_b));
	}
	
	//// angle stuff
	
	dv4 to_rad (dv4 deg) {
		return (dv4)deg * DEG_TO_RADd;
	}
	
	// degress "literal", converts degrees to radiants
	dv4 deg (dv4 deg) {
		return (dv4)deg * DEG_TO_RADd;
	}
	
	dv4 to_deg (dv4 rad) {
		return (dv4)rad * RAD_TO_DEGd;
	}
	
	//// linear algebra ops
	
	// magnitude of vector
	f64 length (dv4 v) {
		return sqrt((f64)(v.x * v.x + v.y * v.y + v.z * v.z + v.w * v.w));
	}
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	f64 length_sqr (dv4 v) {
		return v.x * v.x + v.y * v.y + v.z * v.z + v.w * v.w;
	}
	
	// distance between points, equivalent to length(a - b)
	f64 distance (dv4 a, dv4 b) {
		return length(a - b);
	}
	
	// normalize vector so that it has length() = 1, undefined for zero vector
	dv4 normalize (dv4 v) {
		return dv4(v) / length(v);
	}
	
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	dv4 normalize_or_zero (dv4 v) {
		f64 len = length(v);
		if (len == f64(0)) {
			return f64(0);
		}
		return dv4(v) / dv4(len);
	}
	
	// dot product
	f64 dot (dv4 l, dv4 r) {
		return l.x * r.x + l.y * r.y + l.z * r.z + l.w * r.w;
	}
}// namespace vector

