// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "kissmath.hpp"


#include <string>

#include "dv2.hpp"

namespace vector {
	
	//// matrix forward declarations
	struct f64m3;
	struct f64m4;
	struct f64m2x3;
	struct f64m3x4;
	struct m2;
	
	struct f64m2 {
		dv2 arr[2]; // column major for compatibility with OpenGL
		
		//// Accessors
		
		// get cell with r,c indecies (r=row, c=column)
		f64 get (int r, int c) const;
		// get matrix column
		dv2 get_column (int indx) const;
		// get matrix row
		dv2 get_row (int indx) const;
		
		//// Constructors
		
		f64m2 ();
		// supply one value for all cells
		f64m2 (f64 all);
		// supply all cells, in row major order for readability -> c<r><c> (r=row, c=column)
		f64m2 (
				f64 c00, f64 c01,
				f64 c10, f64 c11);
		
		// static rows() and columns() methods are preferred over constructors, to avoid confusion if column or row vectors are supplied to the constructor
		// supply all row vectors
		static f64m2 rows (dv2 row0, dv2 row1);
		// supply all cells in row major order
		static f64m2 rows (
				f64 c00, f64 c01,
				f64 c10, f64 c11);
		// supply all column vectors
		static f64m2 columns (dv2 col0, dv2 col1);
		// supply all cells in column major order
		static f64m2 columns (
				f64 c00, f64 c10,
				f64 c01, f64 c11);
		
		// identity matrix
		static f64m2 identity ();
		
		// Casting operators
		
		// extend/truncate matrix of other size
		operator f64m3 ();
		// extend/truncate matrix of other size
		operator f64m4 ();
		// extend/truncate matrix of other size
		operator f64m2x3 ();
		// extend/truncate matrix of other size
		operator f64m3x4 ();
		// typecast
		operator m2 ();
		
		// Elementwise operators
		
		f64m2 operator+ (f64m2 m);
		f64m2 operator- (f64m2 m);
	};
	
	f64m2 operator+ (f64m2 l, f64m2 r);
	f64m2 operator- (f64m2 l, f64m2 r);
	f64m2 operator* (f64m2 l, f64m2 r);
	f64m2 operator/ (f64m2 l, f64m2 r);
} // namespace vector

