// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "kissmath.hpp"

#include "fv2.hpp"

namespace vector {
	
	//// matrix forward declarations
	struct fm3;
	struct fm4;
	struct fm2x3;
	struct fm3x4;
	struct dm2;
	
	struct fm2 {
		fv2 arr[2]; // column major for compatibility with OpenGL
		
		//// Accessors
		
		// get cell with r,c indecies (r=row, c=column)
		f32 const& get (int r, int c) const;
		// get matrix column
		fv2 const& get_column (int indx) const;
		// get matrix row
		fv2 get_row (int indx) const;
		
		//// Constructors
		
		fm2 ();
		// supply one value for all cells
		explicit fm2 (f32 all);
		// supply all cells, in row major order for readability -> c<r><c> (r=row, c=column)
		explicit fm2 (
				f32 c00, f32 c01,
				f32 c10, f32 c11);
		
		// static rows() and columns() methods are preferred over constructors, to avoid confusion if column or row vectors are supplied to the constructor
		// supply all row vectors
		static fm2 rows (fv2 row0, fv2 row1);
		// supply all cells in row major order
		static fm2 rows (
				f32 c00, f32 c01,
				f32 c10, f32 c11);
		// supply all column vectors
		static fm2 columns (fv2 col0, fv2 col1);
		// supply all cells in column major order
		static fm2 columns (
				f32 c00, f32 c10,
				f32 c01, f32 c11);
		
		// identity matrix
		static fm2 identity ();
		
		// Casting operators
		
		// extend/truncate matrix of other size
		explicit operator fm3 () const;
		// extend/truncate matrix of other size
		explicit operator fm4 () const;
		// extend/truncate matrix of other size
		explicit operator fm2x3 () const;
		// extend/truncate matrix of other size
		explicit operator fm3x4 () const;
		// typecast
		explicit operator dm2 () const;
		
		// Elementwise operators
		
		fm2& operator+= (f32 r);
		fm2& operator-= (f32 r);
		fm2& operator*= (f32 r);
		fm2& operator/= (f32 r);
		
		// Matrix multiplication
		
		fm2& operator*= (fm2 const& r);
	};
	
	// Elementwise operators
	
	fm2 operator+ (fm2 const& m);
	fm2 operator- (fm2 const& m);
	
	fm2 operator+ (fm2 const& l, fm2 const& r);
	fm2 operator+ (fm2 const& l, f32 r);
	fm2 operator+ (f32 l, fm2 const& r);
	
	fm2 operator- (fm2 const& l, fm2 const& r);
	fm2 operator- (fm2 const& l, f32 r);
	fm2 operator- (f32 l, fm2 const& r);
	
	fm2 mul_elementwise (fm2 const& l, fm2 const& r);
	fm2 operator* (fm2 const& l, f32 r);
	fm2 operator* (f32 l, fm2 const& r);
	
	fm2 div_elementwise (fm2 const& l, fm2 const& r);
	fm2 operator/ (fm2 const& l, f32 r);
	fm2 operator/ (f32 l, fm2 const& r);
	
	// Matrix ops
	
	fm2 operator* (fm2 const& l, fm2 const& r);
	fm2x3 operator* (fm2 const& l, fm2x3 const& r);
	fv2 operator* (fm2 const& l, fv2 r);
	fv2 operator* (fv2 l, fm2 const& r);
	fm2 transpose (fm2 m);
	
	f32 det (fm2 m);
} // namespace vector

