// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "kissmath.hpp"

#include "fv3.hpp"

namespace vector {
	
	//// matrix forward declarations
	struct fm2;
	struct fm4;
	struct fm2x3;
	struct fm3x4;
	struct dm3;
	
	struct fm3 {
		fv3 arr[3]; // column major for compatibility with OpenGL
		
		//// Accessors
		
		// get cell with r,c indecies (r=row, c=column)
		f32 const& get (int r, int c) const;
		// get matrix column
		fv3 const& get_column (int indx) const;
		// get matrix row
		fv3 get_row (int indx) const;
		
		//// Constructors
		
		fm3 ();
		// supply one value for all cells
		explicit fm3 (f32 all);
		// supply all cells, in row major order for readability -> c<r><c> (r=row, c=column)
		explicit fm3 (
				f32 c00, f32 c01, f32 c02,
				f32 c10, f32 c11, f32 c12,
				f32 c20, f32 c21, f32 c22);
		
		// static rows() and columns() methods are preferred over constructors, to avoid confusion if column or row vectors are supplied to the constructor
		// supply all row vectors
		static fm3 rows (fv3 row0, fv3 row1, fv3 row2);
		// supply all cells in row major order
		static fm3 rows (
				f32 c00, f32 c01, f32 c02,
				f32 c10, f32 c11, f32 c12,
				f32 c20, f32 c21, f32 c22);
		// supply all column vectors
		static fm3 columns (fv3 col0, fv3 col1, fv3 col2);
		// supply all cells in column major order
		static fm3 columns (
				f32 c00, f32 c10, f32 c20,
				f32 c01, f32 c11, f32 c21,
				f32 c02, f32 c12, f32 c22);
		
		// identity matrix
		static fm3 identity ();
		
		// Casting operators
		
		// extend/truncate matrix of other size
		explicit operator fm2 () const;
		// extend/truncate matrix of other size
		explicit operator fm4 () const;
		// extend/truncate matrix of other size
		explicit operator fm2x3 () const;
		// extend/truncate matrix of other size
		explicit operator fm3x4 () const;
		// typecast
		explicit operator dm3 () const;
		
		// Elementwise operators
		
		fm3& operator+= (f32 r);
		fm3& operator-= (f32 r);
		fm3& operator*= (f32 r);
		fm3& operator/= (f32 r);
		
		// Matrix multiplication
		
		fm3& operator*= (fm3 const& r);
	};
	
	// Elementwise operators
	
	fm3 operator+ (fm3 const& m);
	fm3 operator- (fm3 const& m);
	
	fm3 operator+ (fm3 const& l, fm3 const& r);
	fm3 operator+ (fm3 const& l, f32 r);
	fm3 operator+ (f32 l, fm3 const& r);
	
	fm3 operator- (fm3 const& l, fm3 const& r);
	fm3 operator- (fm3 const& l, f32 r);
	fm3 operator- (f32 l, fm3 const& r);
	
	fm3 mul_elementwise (fm3 const& l, fm3 const& r);
	fm3 operator* (fm3 const& l, f32 r);
	fm3 operator* (f32 l, fm3 const& r);
	
	fm3 div_elementwise (fm3 const& l, fm3 const& r);
	fm3 operator/ (fm3 const& l, f32 r);
	fm3 operator/ (f32 l, fm3 const& r);
	
	// Matrix ops
	
	fm3 operator* (fm3 const& l, fm3 const& r);
	fm3x4 operator* (fm3 const& l, fm3x4 const& r);
	fv3 operator* (fm3 const& l, fv3 r);
	fv3 operator* (fv3 l, fm3 const& r);
} // namespace vector

