// fv2.cpp generated by vector_srcgen.py
#include "fv2.hpp"

#include "iv2.hpp";
#include "u8v2.hpp";

fv2::operator iv2 () {
	return iv2((int)x, (int)y);
}
fv2::operator u8v2 () {
	return u8v2((u8)x, (u8)y);
}
