// fv3.cpp generated by vector_srcgen.py
#include "fv3.hpp"

#include "iv3.hpp";
#include "u8v3.hpp";

fv3::operator iv3 () {
	return iv3((int)x, (int)y, (int)z);
}
fv3::operator u8v3 () {
	return u8v3((u8)x, (u8)y, (u8)z);
}
