// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#include "fv4.hpp"

#include "fv2.hpp"
#include "fv3.hpp"
#include "bv4.hpp"
#include "bv4.hpp"
#include "dv4.hpp"
#include "iv4.hpp"
#include "s64v4.hpp"
#include "u8v4.hpp"

namespace vector {
	
	
	// extend vector
	fv4::fv4 (fv2 xy, f32 z, f32 w): x{xy.x}, y{xy.y}, z{z}, w{w} {
		
	}
	
	// extend vector
	fv4::fv4 (fv3 xyz, f32 w): x{xyz.x}, y{xyz.y}, z{xyz.z}, w{w} {
		
	}
	
	//// Truncating cast operators
	
	
	fv4::operator fv2 () const {
		return fv2(x, y);
	}
	
	fv4::operator fv3 () const {
		return fv3(x, y, z);
	}
	
	//// Type cast operators
	
	
	fv4::operator bv4 () const {
		return bv4((bool)x, (bool)y, (bool)z, (bool)w);
	}
	
	fv4::operator dv4 () const {
		return dv4((f64)x, (f64)y, (f64)z, (f64)w);
	}
	
	fv4::operator iv4 () const {
		return iv4((s32)x, (s32)y, (s32)z, (s32)w);
	}
	
	fv4::operator s64v4 () const {
		return s64v4((s64)x, (s64)y, (s64)z, (s64)w);
	}
	
	fv4::operator u8v4 () const {
		return u8v4((u8)x, (u8)y, (u8)z, (u8)w);
	}
	
	
	//// arthmethic ops
	
	//// comparison ops
	
	bv4 operator< (fv4 l, fv4 r) {
		return bv4(l.x < r.x, l.y < r.y, l.z < r.z, l.w < r.w);
	}
	
	bv4 operator<= (fv4 l, fv4 r) {
		return bv4(l.x <= r.x, l.y <= r.y, l.z <= r.z, l.w <= r.w);
	}
	
	bv4 operator> (fv4 l, fv4 r) {
		return bv4(l.x > r.x, l.y > r.y, l.z > r.z, l.w > r.w);
	}
	
	bv4 operator>= (fv4 l, fv4 r) {
		return bv4(l.x >= r.x, l.y >= r.y, l.z >= r.z, l.w >= r.w);
	}
	
	bv4 operator== (fv4 l, fv4 r) {
		return bv4(l.x == r.x, l.y == r.y, l.z == r.z, l.w == r.w);
	}
	
	bv4 operator!= (fv4 l, fv4 r) {
		return bv4(l.x != r.x, l.y != r.y, l.z != r.z, l.w != r.w);
	}
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (fv4 l, fv4 r) {
		return all(l == r);
	}
	
	// componentwise ternary c ? l : r
	fv4 select (bv4 c, fv4 l, fv4 r) {
		return c.x ? l.x : r.x, c.y ? l.y : r.y, c.z ? l.z : r.z, c.w ? l.w : r.w;
	}
	
	//// misc ops
	
	fv4 clamp (fv4 x, fv4 a, fv4 b) {
		return min(max(x,a), b);
	}
	
	// get min component of vector, optionally get component index via min_index
	f32 min_component (fv4 v, int* min_index) {
		int index = 0;
		f32 min_val = v.x;	
		for (int i=1; i<4; ++i) {
			if (v.arr[i] <= min_val) {
				index = i;
				min_val = v.arr[i];
			}
		}
		if (min_index) *min_index = index;
		return min_val;
	}
	
	// get max component of vector, optionally get component index via max_index
	f32 max_component (fv4 v, int* max_index) {
		int index = 0;
		f32 max_val = v.x;	
		for (int i=1; i<4; ++i) {
			if (v.arr[i] >= max_val) {
				index = i;
				max_val = v.arr[i];
			}
		}
		if (max_index) *max_index = index;
		return max_val;
	}
	
	
	iv4 floori (fv4 v) {
		return iv4(floori(v.x), floori(v.y), floori(v.z), floori(v.w));
	}
	
	iv4 ceili (fv4 v) {
		return iv4(ceili(v.x), ceili(v.y), ceili(v.z), ceili(v.w));
	}
	
	iv4 roundi (fv4 v) {
		return iv4(roundi(v.x), roundi(v.y), roundi(v.z), roundi(v.w));
	}
	
	
	// linear interpolation t=0 -> a ; t=1 -> b ; t=0.5 -> (a+b)/2
	fv4 lerp (fv4 a, fv4 b, fv4 t) {
		return a * (fv4(1) - t) + b * t;
	}
	
	// linear mapping (reverse linear interpolation), map(70, 0,100) -> 0.7 ; map(0.5, -1,+1) -> 0.75
	fv4 map (fv4 x, fv4 in_a, fv4 in_b) {
		return (x - in_a) / (in_b - in_a);
	}
	
	// linear mapping, lerp(out_a, out_b, map(x, in_a, in_b))
	fv4 map (fv4 x, fv4 in_a, fv4 in_b, fv4 out_a, fv4 out_b) {
		return lerp(out_a, out_b, map(x, in_a, in_b));
	}
	
	//// angle stuff
	
	fv4 to_rad (fv4 deg) {
		return (fv4)deg * DEG_TO_RAD;
	}
	
	// degress "literal", converts degrees to radiants
	fv4 deg (fv4 deg) {
		return (fv4)deg * DEG_TO_RAD;
	}
	
	fv4 to_deg (fv4 rad) {
		return (fv4)rad * RAD_TO_DEG;
	}
	
	//// linear algebra ops
	
	// magnitude of vector
	f32 length (fv4 v) {
		return sqrt((f32)(v.x * v.x + v.y * v.y + v.z * v.z + v.w * v.w));
	}
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	f32 length_sqr (fv4 v) {
		return v.x * v.x + v.y * v.y + v.z * v.z + v.w * v.w;
	}
	
	// distance between points, equivalent to length(a - b)
	f32 distance (fv4 a, fv4 b) {
		return length(a - b);
	}
	
	// normalize vector so that it has length() = 1, undefined for zero vector
	fv4 normalize (fv4 v) {
		return fv4(v) / length(v);
	}
	
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	fv4 normalize_or_zero (fv4 v) {
		f32 len = length(v);
		if (len == f32(0)) {
			return f32(0);
		}
		return fv4(v) / fv4(len);
	}
	
	// dot product
	f32 dot (fv4 l, fv4 r) {
		return l.x * r.x + l.y * r.y + l.z * r.z + l.w * r.w;
	}
}// namespace vector

