// fv4.cpp generated by vector_srcgen.py
#include "fv4.hpp"

#include "iv4.hpp";
#include "u8v4.hpp";

fv4::operator iv4 () {
	return iv4((int)x, (int)y, (int)z, (int)w);
}
fv4::operator u8v4 () {
	return u8v4((u8)x, (u8)y, (u8)z, (u8)w);
}
