// iv4.cpp generated by vector_srcgen.py
#include "iv4.hpp"

#include "fv4.hpp";
#include "dv4.hpp";

iv4::operator fv4 () {
	return fv4((f32)x, (f32)y, (f32)z, (f32)w);
}
iv4::operator dv4 () {
	return dv4((f64)x, (f64)y, (f64)z, (f64)w);
}
