// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py

blah mymod (blah x, blah y) {
	// BLah 1
	T modded = x % y;
	if (range > 0) {
		if (modded < 0) modded += range;
	} else {
		if (modded > 0) modded -= range;
	}
	return modded;
}

// BLah 2
blah mymod (blah x, blah y) {
	T modded = x % y;
	if (range > 0) {
		if (modded < 0) modded += range;
	} else {
		if (modded > 0) modded -= range;
	}
	return modded;
}
