// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#include "m2.hpp"

#include "m3.hpp"
#include "m4.hpp"
#include "m2x3.hpp"
#include "m3x4.hpp"
#include "f64m2.hpp"

namespace vector {
	
	//// Accessors
	
	
	f32 m2::get (int r, int c) const {
		return arr[c][r];
	}
	
	fv2 m2::get_column (int indx) const {
		return arr[indx];
	}
	
	fv2 m2::get_row (int indx) const {
		return fv2(arr[0][indx], arr[1][indx]);
	}
	
	//// Constructors
	
	
	m2::m2 () {
		
	}
	
	m2::m2 (f32 all): 
	arr{
		fv2(all, all),
		fv2(all, all)} {
		
	}
	
	m2::m2 (
			f32 c00, f32 c01,
			f32 c10, f32 c11): 
	arr{
		fv2(c00, c10),
		fv2(c01, c11)} {
		
	}
	
	// static rows() and columns() methods are preferred over constructors, to avoid confusion if column or row vectors are supplied to the constructor
	
	m2 m2::rows (fv2 row0, fv2 row1) {
		return m2(
				row0[0], row0[1],
				row1[0], row1[1]);
	}
	
	m2 m2::rows (
			f32 c00, f32 c01,
			f32 c10, f32 c11) {
		return m2(
				c00, c01,
				c10, c11);
	}
	
	m2 m2::columns (fv2 col0, fv2 col1) {
		return m2(
				col0[0], col1[0],
				col0[1], col1[1]);
	}
	
	m2 m2::columns (
			f32 c00, f32 c10,
			f32 c01, f32 c11) {
		return m2(
				c00, c01,
				c10, c11);
	}
	
	
	m2 m2::identity () {
		return m2(
				1,0,
				0,1);
	}
	
	// Casting operators
	
	
	m2::operator m3 () {
		return m3(
				arr[0][0], arr[1][0],         0,
				arr[0][1], arr[1][1],         0,
				        0,         0,         1);
	}
	
	m2::operator m4 () {
		return m4(
				arr[0][0], arr[1][0],         0,         0,
				arr[0][1], arr[1][1],         0,         0,
				        0,         0,         1,         0,
				        0,         0,         0,         1);
	}
	
	m2::operator m2x3 () {
		return m2x3(
				arr[0][0], arr[1][0],         0,
				arr[0][1], arr[1][1],         0);
	}
	
	m2::operator m3x4 () {
		return m3x4(
				arr[0][0], arr[1][0],         0,         0,
				arr[0][1], arr[1][1],         0,         0,
				        0,         0,         1,         0);
	}
	
	m2::operator f64m2 () {
		return f64m2(
				(f64)arr[0][0], (f64)arr[0][1],
				(f64)arr[1][0], (f64)arr[1][1]);
	}
	
	// Elementwise operators
	
	
	m2 m2::operator+ (m2 m) {
		return m2(
				+m.arr[0][0], +m.arr[1][0],
				+m.arr[0][1], +m.arr[1][1]);
	}
	
	m2 m2::operator- (m2 m) {
		return m2(
				-m.arr[0][0], -m.arr[1][0],
				-m.arr[0][1], -m.arr[1][1]);
	}
	
	m2 operator+ (m2 l, m2 r) {
		return m2(
				l.arr[0][0] + r.arr[0][0], l.arr[1][0] + r.arr[1][0],
				l.arr[0][1] + r.arr[0][1], l.arr[1][1] + r.arr[1][1]);
	}
	
	m2 operator- (m2 l, m2 r) {
		return m2(
				l.arr[0][0] - r.arr[0][0], l.arr[1][0] - r.arr[1][0],
				l.arr[0][1] - r.arr[0][1], l.arr[1][1] - r.arr[1][1]);
	}
	
	m2 operator* (m2 l, m2 r) {
		return m2(
				l.arr[0][0] * r.arr[0][0], l.arr[1][0] * r.arr[1][0],
				l.arr[0][1] * r.arr[0][1], l.arr[1][1] * r.arr[1][1]);
	}
	
	m2 operator/ (m2 l, m2 r) {
		return m2(
				l.arr[0][0] / r.arr[0][0], l.arr[1][0] / r.arr[1][0],
				l.arr[0][1] / r.arr[0][1], l.arr[1][1] / r.arr[1][1]);
	}
} // namespace vector

