// u8v2.cpp generated by vector_srcgen.py
#include "u8v2.hpp"

#include "fv2.hpp";
#include "dv2.hpp";

u8v2::operator fv2 () {
	return fv2((f32)x, (f32)y);
}
u8v2::operator dv2 () {
	return dv2((f64)x, (f64)y);
}
