// u8v2.hpp generated by vector_srcgen.py
#pragma once

#include "kissmath.hpp"

// forward declarations for conversion operators
union fv2;
union dv2;

union u8v2 {
	struct {
		u8	x, y;
	};
	u8		arr[2];

	inline u8& operator[] (int i) {
		return arr[i];
	}

	inline u8v2 () {
	
	}

	inline constexpr u8v2 (u8 all): x{all}, y{all} {
	
	}

	inline constexpr u8v2 (u8 x, u8 y): x{x}, y{y} {
	
	}

	inline u8v2 operator+= (u8v2 r) {
		x += r.x;
		y += r.y;
		return *this;
	}
	inline u8v2 operator-= (u8v2 r) {
		x -= r.x;
		y -= r.y;
		return *this;
	}
	inline u8v2 operator*= (u8v2 r) {
		x *= r.x;
		y *= r.y;
		return *this;
	}
	inline u8v2 operator/= (u8v2 r) {
		x /= r.x;
		y /= r.y;
		return *this;
	}

	operator fv2 ();
	operator dv2 ();
};

