// u8v4.hpp generated by vector_srcgen.py
#pragma once

#include "kissmath.hpp"

// forward declarations for conversion operators
union fv4;
union dv4;

union u8v4 {
	struct {
		u8	x, y, z, w;
	};
	u8		arr[4];

	inline u8& operator[] (int i) {
		return arr[i];
	}

	inline u8v4 () {
	
	}

	inline constexpr u8v4 (u8 all): x{all}, y{all}, z{all}, w{all} {
	
	}

	inline constexpr u8v4 (u8 x, u8 y, u8 z, u8 w): x{x}, y{y}, z{z}, w{w} {
	
	}

	inline u8v4 operator+= (u8v4 r) {
		x += r.x;
		y += r.y;
		z += r.z;
		w += r.w;
		return *this;
	}
	inline u8v4 operator-= (u8v4 r) {
		x -= r.x;
		y -= r.y;
		z -= r.z;
		w -= r.w;
		return *this;
	}
	inline u8v4 operator*= (u8v4 r) {
		x *= r.x;
		y *= r.y;
		z *= r.z;
		w *= r.w;
		return *this;
	}
	inline u8v4 operator/= (u8v4 r) {
		x /= r.x;
		y /= r.y;
		z /= r.z;
		w /= r.w;
		return *this;
	}

	operator fv4 ();
	operator dv4 ();
};

