// generated by C:\Users\Me\Desktop\kiss\vector_srcgen\srcgen.py
#pragma once

#include "kissmath.hpp"

// Vectors
#include "bv2.hpp"
#include "bv3.hpp"
#include "bv4.hpp"

#include "fv2.hpp"
#include "fv3.hpp"
#include "fv4.hpp"

#include "dv2.hpp"
#include "dv3.hpp"
#include "dv4.hpp"

#include "iv2.hpp"
#include "iv3.hpp"
#include "iv4.hpp"

#include "s64v2.hpp"
#include "s64v3.hpp"
#include "s64v4.hpp"

#include "u8v2.hpp"
#include "u8v3.hpp"
#include "u8v4.hpp"

// Typedefs that define 'standart' floats to use across program
typedef float flt;

typedef fv2 v2;
typedef fv3 v3;
typedef fv4 v4;

